name: home_cloud
description: A new Flutter project for Home Cloud.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^13.2.0

  # Networking
  dio: ^5.4.1

  # UI/Assets
  flutter_animate: ^4.5.0
  percent_indicator: ^4.2.3
  cached_network_image: ^3.3.1
  
  # Media Management
  video_player: ^2.8.3
  chewie: ^1.7.5
  audioplayers: ^6.0.0
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_windows_video: ^1.0.8

  # File & System
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  open_filex: ^4.4.0
  permission_handler: ^11.3.0
  
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.5.4
  window_manager: ^0.5.1
  watcher: ^1.2.1
  tray_manager: ^0.5.2
  launch_at_startup: ^0.5.1
  path: ^1.9.1
  package_info_plus: ^9.0.0
  workmanager: ^0.9.0
  device_info_plus: ^12.3.0
  flutter_foreground_task: ^9.2.0
  flutter_local_notifications: ^19.1.0
  media_kit_libs_linux: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.10
  msix: ^3.16.8


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
  
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/font/PlusJakartaSans-Regular.ttf
        - asset: assets/font/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: assets/font/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/font/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/font/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/font/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/font/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/font/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/font/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/font/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/font/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/font/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/font/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic

    - family: Open Sans
      fonts:
        - asset: assets/font/open_sans_medium.ttf
          weight: 500
        - asset: assets/font/open_sans_semibold.ttf
          weight: 600
        - asset: assets/font/open_sans_bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_logo.png"
  adaptive_icon_background: "#FFFFFF"


  windows:
    generate: true
    image_path: "assets/icon/app_logo.png"
    icon_size: 256

msix_config:
  display_name: Home Cloud
  publisher_display_name: HomeCloud
  identity_name: com.homecloud.app
  msix_version: 1.0.0.0
  logo_path: assets/icon/app_logo.png
  install_certificate: false
  capabilities: "internetClient, privateNetworkClientServer"
